### ISSUE TITLE
Download Link Expires

### ISSUE THREAD

**Issue by MauriceNino** [rlucente-se-jboss/jbds-via-html5#2]
```
oc new-build https://github.com/rlucente-se-jboss/jbds-via-html5 \
    --name=jbds --strategy=docker
oc cancel-build jbds-1
oc start-build jbds \
    -e JBDS_JAR=devstudio-10.4.0.GA-installer-standalone.jar \
    -e INSTALLER_URL=<direct-link-URL>
```
When the build comes to the point of downloading the file, the dl link is expired and doesnt work anymore

**Comment by rlucente-retro** [comment]
This absolutely can happen.  I'll update the instructions with alternative ways to host the distributable file for the jbds installer.

**Comment by rlucente-retro** [comment]
Update to instructions via 30111ab
